# Generated by Django 4.2.7 on 2023-12-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='rahim', max_length=20),
            preserve_default=False,
        ),
    ]
